### ISSUE TITLE
"Syntax error in text – mermaid version 10.9.2"

### ISSUE THREAD

**Issue by OliverO2** [serras/fir-tree#27]
Versions: FIR Tree 0.4.0, IntelliJ IDEA 2024.2.3 (Ultimate Edition)

I could produce "Syntax error in text – mermaid version 10.9.2" with the following Kotlin source in a Kotlin scratch file, then selecting `FirSimpleFunction`, then clicking "Control Flow Graph":

```kotlin
import testFramework.compilerPlugin.compilation

fun X() {
    val d = "$"
    compilation(
        """
                val some = "text"
                fun some() = "text"

                fun test(name: String) {}
                
                fun use() {
                    test("constant string")
                    test("string with $d{some} param")
                    test("string with $d{some()} param")
                }
            """,
        debugEnabled = true
    ) {
    }
}
```

It did not always reproduce. Switching to another file and back sometimes helped.

**Comment by serras** [comment]
Fixed by c8fbf06149ecd29777f9c0ddc227d060c3cc9007

The new 0.4.2 version is now in the process of publication
